name: runningman_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.2.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  tutorial_coach_mark: ^1.2.11
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  flutter_local_notifications: ^18.0.1
  audioplayers: ^6.1.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
  remove_alpha_ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/data/
    - assets/alphabet_audio/
    - assets/decorations/
    - assets/images/1/
    - assets/images/2/
    - assets/onboarding/
